/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;


import classes.Pessoas;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

import persistencia.ConexaoSql;

/**
 *
 * @author fernando
 */
public class Cadastro extends javax.swing.JInternalFrame {
    
    
  
    int acao;
    String nome;
    int estado_civil;
    String data_de_nascimento;
    String telefone;
    String celular;
    String data_de_cadastro;
    String rg;
    String cpf;
    String endereco;
    String numero;
    String complemento;
    String comentarios;
    String email;
    String numeroDeProcesso;
    boolean status;
    String cep;
    String nome2;
    String nome3;
    String assunto;
    String justica;
    String instancia;
    String orgao;
    String pessoa;
    
    
    
    String comandoSql;
   public String variaveisDoBD= "nome,estado_civil,data_de_nascimento,telefone,celular,"
           + "data_de_cadastro,rg,cpf,endereco,numero,complemento,email,"
           + "comentarios,status,cep,numero_de_processo,nome2,nome3,assunto,justica"
           + ",instancia,orgao,pessoa";
   public String interrogacoes= "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?";
    

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jtfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnProcurarCod = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jftfDataDeCadastro = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaComentarios = new javax.swing.JTextArea();
        jtfEndereco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbEstadoCivil = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jbtnLimpar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jcbStatus = new java.awt.Checkbox();
        jbtnCod = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jftfCep = new javax.swing.JFormattedTextField();
        jftfCodigo = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jtfNome2 = new javax.swing.JTextField();
        jtfNome3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jftfNumeroDeProcesso = new javax.swing.JFormattedTextField();
        btnProcurarNP = new javax.swing.JButton();
        jlblSalvoComSucesso = new javax.swing.JLabel();
        jftfCpf = new javax.swing.JFormattedTextField();
        jftfDataDeNascimento = new javax.swing.JFormattedTextField();
        jftfTelefone = new javax.swing.JFormattedTextField();
        jftfCelular = new javax.swing.JFormattedTextField();
        jftfRg = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtfAssunto = new javax.swing.JTextField();
        jtfJustica = new javax.swing.JTextField();
        jtfInstancia = new javax.swing.JTextField();
        jtfOrgao = new javax.swing.JTextField();
        jcbPessoa = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Nome (Titular) ");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setEnabled(false);
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jbtnEditar.setText("Editar");
        jbtnEditar.setEnabled(false);
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });

        jtfNome.setEnabled(false);
        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nümero:");

        jtfNumero.setEnabled(false);

        jLabel3.setText("Telefone");

        jLabel4.setText("RG");

        jLabel5.setText("CPF");

        jLabel6.setText("Celular");

        jLabel7.setText("Cod.:");

        btnProcurarCod.setText("Procurar");
        btnProcurarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarCodActionPerformed(evt);
            }
        });

        jLabel8.setText("Data do cadastro:");

        jftfDataDeCadastro.setEnabled(false);

        jLabel10.setText("Endereco:");

        jtaComentarios.setBackground(new java.awt.Color(204, 204, 204));
        jtaComentarios.setColumns(20);
        jtaComentarios.setLineWrap(true);
        jtaComentarios.setRows(5);
        jtaComentarios.setEnabled(false);
        jScrollPane1.setViewportView(jtaComentarios);

        jtfEndereco.setEnabled(false);

        jLabel11.setText("Complemento");

        jtfComplemento.setEnabled(false);

        jLabel12.setText("Comentarios");

        jLabel13.setText("Estado Civil");

        jcbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar...", "Solteiro(a)", "Casado(a)", "Viúvo(a)", "Divorciado(a)", "Separado", "Outros" }));
        jcbEstadoCivil.setEnabled(false);
        jcbEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadoCivilActionPerformed(evt);
            }
        });

        jLabel14.setText("Data de Nascimento");

        jbtnLimpar.setText("Limpar");
        jbtnLimpar.setEnabled(false);
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });

        jLabel15.setText("Status");

        jLabel16.setText("E-mail");

        jtfEmail.setEnabled(false);

        jcbStatus.setEnabled(false);
        jcbStatus.setLabel("Cliente ativo");

        jbtnCod.setText("Pesquisar por Código");
        jbtnCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCodActionPerformed(evt);
            }
        });

        jLabel17.setText("CEP");

        try {
            jftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jftfCep.setEnabled(false);
        jftfCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftfCepActionPerformed(evt);
            }
        });

        jftfCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftfCodigoActionPerformed(evt);
            }
        });
        jftfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jftfCodigoKeyTyped(evt);
            }
        });

        jLabel18.setText("Nome(Opcional)");

        jtfNome2.setEnabled(false);
        jtfNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNome2ActionPerformed(evt);
            }
        });

        jtfNome3.setEnabled(false);
        jtfNome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNome3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Nº do processo");

        try {
            jftfNumeroDeProcesso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-##.####.#.##.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnProcurarNP.setText("Procurar");
        btnProcurarNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarNPActionPerformed(evt);
            }
        });

        jlblSalvoComSucesso.setForeground(new java.awt.Color(255, 0, 0));
        jlblSalvoComSucesso.setText("Salvo com Sucesso");

        jftfCpf.setEnabled(false);

        try {
            jftfDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfDataDeNascimento.setEnabled(false);
        jftfDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftfDataDeNascimentoActionPerformed(evt);
            }
        });

        try {
            jftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfTelefone.setEnabled(false);

        try {
            jftfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCelular.setEnabled(false);

        jftfRg.setEnabled(false);

        jLabel21.setText("Nome(Opcional)");

        jLabel19.setText("Pessoa");

        jLabel20.setText("Assunto");

        jLabel23.setText("Justiça");

        jLabel24.setText("Instancia");

        jLabel25.setText("Orgão");

        jtfAssunto.setEnabled(false);

        jtfJustica.setEnabled(false);

        jtfInstancia.setEnabled(false);

        jtfOrgao.setEnabled(false);

        jcbPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fisica", "Juridica" }));
        jcbPessoa.setEnabled(false);
        jcbPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel15)
                                .addGap(9, 9, 9)
                                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftfDataDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblSalvoComSucesso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCod, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(2, 2, 2)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(4, 4, 4)
                                                .addComponent(jftfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(btnProcurarCod))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(5, 5, 5)
                                                .addComponent(jcbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(70, 70, 70)
                                                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jtfNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(4, 4, 4)
                                        .addComponent(jftfDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(btnProcurarNP))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jftfNumeroDeProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(21, 21, 21))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel4)
                                        .addGap(6, 6, 6)
                                        .addComponent(jftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtfEndereco))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(9, 9, 9)
                                                .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel6)
                                                .addGap(6, 6, 6)
                                                .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2))
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel11)
                                        .addGap(5, 5, 5)
                                        .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfAssunto, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(jtfJustica)
                                    .addComponent(jtfInstancia)
                                    .addComponent(jtfOrgao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(btnExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7))
                            .addComponent(jftfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(btnProcurarCod)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jcbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jftfNumeroDeProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnExcluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProcurarNP)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jftfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jtfAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jtfJustica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jtfInstancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jtfOrgao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnCod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jbtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jbtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jbtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jftfDataDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jlblSalvoComSucesso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int certeza= JOptionPane.showConfirmDialog(this, "Voce tem certeza que deseja excluir este cadastro?");
        System.out.println(certeza);
        if (certeza==0){
        Pessoas cliente =new Pessoas();
        
       
        int codigo =Integer.parseInt(jftfCodigo.getText());
        ConexaoSql conexao = new ConexaoSql();
        ResultSet resultSet = null;
        Statement statement = null;
        conexao.conectar();
        String query = "DELETE FROM dados_cadastrais2 WHERE cod = " +codigo;
        statement = conexao.criarStatement();
        try{
           resultSet=statement.executeQuery(query);
         
        }
        catch(SQLException e){
            System.out.println(e.getMessage());
            
        }
        finally{
            try {
                
                statement.close();
                conexao.desconectar();
                limpar_campos();
            }
        catch(SQLException e){
                System.out.println(e.getMessage());
        }}}
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        // TODO add your handling code here:
        jlblSalvoComSucesso.setVisible(false);
       jbtnCod.setEnabled(true);
        habilitar();
        acao=0;
        
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        btnProcurarCod.setEnabled(false);
        btnProcurarNP.setEnabled(false);
        limpar_campos();
        jlblSalvoComSucesso.setVisible(false);
        jbtnCod.setVisible(true);
        habilitar();
        jbtnEditar.setEnabled(false);
        acao= 1;
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        Date data_atual= new Date();
        String data= formatador.format(data_atual);
        
                
        
        
        jftfDataDeCadastro.setText(data);
       
    }//GEN-LAST:event_btnNovoActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        // TODO add your handling code here:
        
        ConexaoSql conexao = new ConexaoSql();
        Pessoas DadosDasPessoas= new Pessoas();
        
        
        conexao.conectar();
        conexao.criarTabelaCliente();
        
        
        
       
        
        
        nome= jtfNome.getText();
        estado_civil= jcbEstadoCivil.getSelectedIndex();
        data_de_nascimento= jftfDataDeNascimento.getText();
        telefone= jftfTelefone.getText();
        celular= jftfCelular.getText();
        data_de_cadastro= jftfDataDeCadastro.getText();
        rg= jftfRg.getText();
        cpf= jftfCpf.getText();
        endereco= jtfEndereco.getText();
        cep=jftfCep.getText();
        numero= jtfNumero.getText();
        complemento= jtfComplemento.getText();
        email=jtfEmail.getText();
        comentarios= jtaComentarios.getText();
        status= jcbStatus.getState();
        numeroDeProcesso= jftfNumeroDeProcesso.getText();        //,nome2,nome3,assunto,justica,instancia,orgao,pessoa";
        nome2= jtfNome2.getText();
        nome3 = jtfNome3.getText();
        assunto= jtfAssunto.getText();
        justica=jtfJustica.getText();
        orgao=jtfOrgao.getText();
        pessoa=jcbPessoa.getSelectedItem().toString();
        instancia=jtfInstancia.getText();
        
      
        // colocando dados em variaveis
        
        
        
        
        
            Pessoas cliente = new Pessoas();

    cliente.setNome(nome);
    cliente.setEstado_civil(estado_civil);
    cliente.setData_de_nascimento(data_de_nascimento);
    cliente.setTelefone(telefone);
    cliente.setCelular(celular);
    cliente.setData_de_cadastro(data_de_cadastro);
    cliente.setRg(rg);
    cliente.setCpf(cpf);
    cliente.setEndereco(endereco);
    cliente.setNumero(numero);
    cliente.setComplemento(complemento);
    cliente.setEmail(email);
    cliente.setComentarios(comentarios);
    cliente.setStatus(status);
    cliente.setCep(cep);
    cliente.setNumero_de_processo(numeroDeProcesso);
    cliente.setNome2(nome2);
    cliente.setNome3(nome3);                 //,nome2,nome3,assunto,justica,instancia,orgao,pessoa";
    cliente.setAssunto(assunto);
    cliente.setJustica(justica);
    cliente.setInstancia(instancia);
    cliente.setOrgao(orgao);
    cliente.setPessoa(pessoa);
        System.out.println(cliente.getStatus());
    
    
    int acao_anterior;
    acao_anterior=acao;
    if("".equals(jtfNome.getText())){
        
        acao=2;
        JOptionPane.showMessageDialog(this,"Digite o nome");
    }
    if (acao==1){
 
    
  

     String sqlInsert = " INSERT INTO dados_cadastrais2 ("+ variaveisDoBD
                
                + ")VALUES" + "("+interrogacoes +");"
             ;
        System.out.println(sqlInsert);
        conexao.conectar();
         PreparedStatement preparedStatement = conexao.criarPreparedStatement(sqlInsert);
        try {
            preparedStatement.setString(1, cliente.getNome());
            preparedStatement.setInt(2, cliente.getEstado_civil()); 
            preparedStatement.setString(3, cliente.getData_de_nascimento());
            preparedStatement.setString(4, cliente.getTelefone());
            preparedStatement.setString(5, cliente.getCelular());
            preparedStatement.setString(6, cliente.getData_de_cadastro());            
            preparedStatement.setString(7, cliente.getRg());
            preparedStatement.setString(8, cliente.getCpf());
            preparedStatement.setString(9, cliente.getEndereco());
            preparedStatement.setString(10, cliente.getNumero());
            preparedStatement.setString(11, cliente.getComplemento());
            preparedStatement.setString(12, cliente.getEmail());
            preparedStatement.setString(13, cliente.getComentarios());
            preparedStatement.setBoolean(14, cliente.getStatus());
            preparedStatement.setString(15, cliente.getCep());
            preparedStatement.setString(16, cliente.getNumero_de_processo());
            preparedStatement.setString(17,cliente.getNome2());                             //,nome2,nome3,assunto,justica,instancia,orgao,pessoa";
            preparedStatement.setString(18,cliente.getNome3());
            preparedStatement.setString(19,cliente.getAssunto());
            preparedStatement.setString(20,cliente.getJustica());
            preparedStatement.setString(21,cliente.getInstancia());
            preparedStatement.setString(22,cliente.getOrgao());
            preparedStatement.setString(23,cliente.getPessoa());
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
        
        
       try {
           preparedStatement.execute();
           limpar_campos();
           jlblSalvoComSucesso.setVisible(true);
           
        
            

           

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally{
            if(preparedStatement != null){
                try {
                    preparedStatement.close();
                    conexao.desconectar();
                    desabilitar();
                } catch (SQLException ex) {
                    Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }
    if(acao==0){String sqlInsert = " UPDATE dados_cadastrais2 SET"
            + " nome=?, "
            + "estado_civil=?,"
            + "data_de_nascimento=?,"
            + "telefone=?,"
            + "celular=?,"
            + "data_de_cadastro=?,"
            + "rg=?,"
            + "cpf=?,"
            + "endereco=?,"
            + "numero=?,"
            + "complemento=?,"
            + "email=?,"
            + "comentarios=?,"
            + "status=?,"
            + "cep=?,"
            + "numero_de_processo=?,"
            + "nome2=?,"
            + "nome3=?,"
            + "assunto=?,"
            + "justica=?,"
            + "instancia=?,"
            + "orgao=?,"
            + "pessoa=?"
               
                + "WHERE cod== "+ jftfCodigo.getText()
                + ";";
        System.out.println(sqlInsert);
      conexao.conectar();
    PreparedStatement preparedStatement = conexao.criarPreparedStatement(sqlInsert);
        try {
            preparedStatement.setString(1, cliente.getNome());
            preparedStatement.setInt(2, cliente.getEstado_civil()); 
            preparedStatement.setString(3, cliente.getData_de_nascimento());
            preparedStatement.setString(4, cliente.getTelefone());
            preparedStatement.setString(5, cliente.getCelular());
            preparedStatement.setString(6, cliente.getData_de_cadastro());            
            preparedStatement.setString(7, cliente.getRg());
            preparedStatement.setString(8, cliente.getCpf());
            preparedStatement.setString(9, cliente.getEndereco());
            preparedStatement.setString(10, cliente.getNumero());
            preparedStatement.setString(11, cliente.getComplemento());
            preparedStatement.setString(12, cliente.getEmail());
            preparedStatement.setString(13, cliente.getComentarios());
            preparedStatement.setBoolean(14, cliente.getStatus());
            preparedStatement.setString(15, cliente.getCep());
            preparedStatement.setString(16, cliente.getNumero_de_processo());
            preparedStatement.setString(17,cliente.getNome2());                             //,nome2,nome3,assunto,justica,instancia,orgao,pessoa";
            preparedStatement.setString(18,cliente.getNome3());
            preparedStatement.setString(19,cliente.getAssunto());
            preparedStatement.setString(20,cliente.getJustica());
            preparedStatement.setString(21,cliente.getInstancia());
            preparedStatement.setString(22,cliente.getOrgao());
            preparedStatement.setString(23,cliente.getPessoa());
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       try {
           preparedStatement.execute();
           limpar_campos();
           
           jlblSalvoComSucesso.setVisible(true);
           
        
            

           

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } finally{
            if(preparedStatement != null){
                try {
                    preparedStatement.close();
                    conexao.desconectar();
                    desabilitar();
                    jftfCodigo.setEnabled(true);
                    btnProcurarNP.setEnabled(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
       if (acao!=1 && acao!=0){
           acao=acao_anterior;
       }
       
        
        
    }
    

    
    
    
        
            
            
    
    cliente.setComentarios(comentarios);
        
    
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void btnProcurarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarCodActionPerformed
        // TODO add your handling code here:
        
        jlblSalvoComSucesso.setVisible(false);
        if ("".equals(jftfCodigo.getText())){
       //      JOptionPane.showMessageDialog(frame,
      //  "Houve um problema ao procurar o batman:\n\n '" + erro + "'.", //mensagem
       // "Erro 404", // titulo da janela 
      //  JOptionPane.INFORMATION_MESSAGE);
      JOptionPane.showMessageDialog(this,"Insira algum valor no campo de código");}
        else{
            System.out.println("else");
        Pessoas cliente =new Pessoas();
        //limpando campos
        jtfNome.setText("");
        jtfNome2.setText("");
        jtfNome3.setText("");
        jcbEstadoCivil.setSelectedIndex(0);
        jftfDataDeNascimento.setText("");
        jftfTelefone.setText("");
        jftfCelular.setText("");
        jftfDataDeCadastro.setText("");
        jftfRg.setText("");
        jftfCpf.setText("");
        jtfEndereco.setText("");
        jtfNumero.setText("");
        jtfComplemento.setText("");
        jtfEmail.setText("");
        jtaComentarios.setText("");
        jcbStatus.setState(true);
        jftfCep.setText("");
        jftfNumeroDeProcesso.setText("");
        jtfAssunto.setText("");
        jtfJustica.setText("");
        jtfInstancia.setText("");
        jtfOrgao.setText("");
        jcbPessoa.setSelectedIndex(0);
        
        
        
       
        int codigo =Integer.parseInt(jftfCodigo.getText());
        ConexaoSql conexao = new ConexaoSql();
        ResultSet resultSet = null;
        Statement statement = null;
        conexao.conectar();
        String query = "SELECT * FROM dados_cadastrais2 where cod==" +codigo;
        statement = conexao.criarStatement();
        try{
           resultSet=statement.executeQuery(query);
        
           while(resultSet.next()){
               
               
               jtfNome.setText(resultSet.getString("nome"));
               
                jcbEstadoCivil.setSelectedIndex(Integer.parseInt(resultSet.getString("estado_civil")));
                jftfDataDeNascimento.setText(resultSet.getString("data_de_nascimento"));
                jftfTelefone.setText(resultSet.getString("telefone"));
                jftfCelular.setText(resultSet.getString("celular"));
                jftfDataDeCadastro.setText(resultSet.getString("data_de_cadastro"));
                jftfRg.setText(resultSet.getString("rg"));
                jftfCpf.setText(resultSet.getString("cpf"));
                jtfEndereco.setText(resultSet.getString("endereco"));
                jtfNumero.setText(resultSet.getString("numero"));
                jftfCep.setText(resultSet.getString("cep"));
                jtfComplemento.setText(resultSet.getString("complemento"));
                jftfNumeroDeProcesso.setText(resultSet.getString("numero_de_processo"));
                jtfEmail.setText(resultSet.getString("email"));
                jtaComentarios.setText(resultSet.getString("comentarios"));
                if((resultSet.getString("status"))=="1"){
                jcbStatus.setState(true);}
                else{
                     jcbStatus.setState(false);
                }
                jtfNome2.setText(resultSet.getString("nome2"));
                jtfNome3.setText(resultSet.getString("nome3"));
                jtfAssunto.setText(resultSet.getString("assunto"));
                jtfJustica.setText(resultSet.getString("justica"));
                jtfInstancia.setText(resultSet.getString("instancia"));
                jtfOrgao.setText(resultSet.getString("orgao"));
                if (resultSet.getString("pessoa").equals("Fisica")){
                    jcbPessoa.setSelectedIndex(0);
                }
                else{
                    jcbPessoa.setSelectedIndex(1);
                }
                jbtnEditar.setEnabled(true);
                   if(resultSet.wasNull()){
               JOptionPane.showMessageDialog(this,"Cliente não encontrado");}

               
           }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Cliente não encontrado");
            
            System.out.println(e.getMessage());
          
            
            
        }
        
        finally{
            try {
     
                resultSet.close();
            
                statement.close();
                conexao.desconectar();
                
            }
        catch(SQLException e){
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this,"Cliente não encontrado");
        }}}
        if(jtfNome.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Cliente não encontrado");
            
        }
        else{
            jbtnEditar.setEnabled(true);
            jftfNumeroDeProcesso.setEnabled(true);
            btnProcurarNP.setEnabled(false);
            System.out.println("editar devia aparecer");
        }
        
    }//GEN-LAST:event_btnProcurarCodActionPerformed

    private void jcbEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbEstadoCivilActionPerformed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        // TODO add your handling code here:
         jtfNome.setText("");
        jtfNome2.setText("");
        jtfNome3.setText("");
        jcbEstadoCivil.setSelectedIndex(0);
        jftfDataDeNascimento.setText("");
        jftfTelefone.setText("");
        jftfCelular.setText("");
       
        jftfRg.setText("");
        jftfCpf.setText("");
        jtfEndereco.setText("");
        jtfNumero.setText("");
        jtfComplemento.setText("");
        jtfEmail.setText("");
        jtaComentarios.setText("");
        jcbStatus.setState(true);
        jftfCodigo.setText("");
        jftfNumeroDeProcesso.setText("");
        jtfAssunto.setText("");
        jtfJustica.setText("");
        jtfInstancia.setText("");
        jtfOrgao.setText("");
        jcbPessoa.setSelectedIndex(0);
        
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        jbtnCod.setVisible(false);
        ConexaoSql conexao= new ConexaoSql();
        conexao.criarTabelaCliente();
        
        jlblSalvoComSucesso.setVisible(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbtnCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCodActionPerformed
        // TODO add your handling code here:
        desabilitar();
        btnProcurarNP.setEnabled(true);
        btnProcurarCod.setEnabled(true);
        jftfCodigo.setEnabled(true);
        jlblSalvoComSucesso.setVisible(false);
        jftfCodigo.setText("");
        jbtnCod.setVisible(false);
    }//GEN-LAST:event_jbtnCodActionPerformed

    private void jtfNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNome2ActionPerformed

    private void jtfNome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNome3ActionPerformed

    private void btnProcurarNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarNPActionPerformed
        // TODO add your handling code here:
        Pessoas cliente =new Pessoas();
        jlblSalvoComSucesso.setVisible(false);
       
        
       
        String numeroDeProcesso =jftfNumeroDeProcesso.getText();
        ConexaoSql conexao = new ConexaoSql();
        ResultSet resultSet = null;
        Statement statement = null;
        conexao.conectar();
        String query = "SELECT * FROM dados_cadastrais2 where numero_de_processo==" +numeroDeProcesso;
        statement = conexao.criarStatement();
        try{
           resultSet=statement.executeQuery(query);
           while(resultSet.next()){
               System.out.println("uhu pesquisou!");
               
               
               jtfNome.setText(resultSet.getString("nome"));
               
                jcbEstadoCivil.setSelectedIndex(0);
                jftfDataDeNascimento.setText(resultSet.getString("data_de_nascimento"));
                jftfTelefone.setText(resultSet.getString("telefone"));
                jftfCelular.setText(resultSet.getString("celular"));
                jftfDataDeCadastro.setText(resultSet.getString("data_de_cadastro"));
                jftfRg.setText(resultSet.getString("rg"));
                jftfCpf.setText(resultSet.getString("cpf"));
                jtfEndereco.setText(resultSet.getString("endereco"));
                jtfNumero.setText(resultSet.getString("numero"));
                
                jtfComplemento.setText(resultSet.getString("complemento"));
                
                jtfEmail.setText(resultSet.getString("email"));
                jtaComentarios.setText(resultSet.getString("comentarios"));
                jftfNumeroDeProcesso.setText(resultSet.getString("numero_de_processo"));
                jftfCep.setText(resultSet.getString("cep"));
                if((resultSet.getString("status"))=="1"){
                jcbStatus.setState(true);}
                
                else{
                     jcbStatus.setState(false);                               //"comentarios,status,cep,numero_de_processo,nome2,nome3,assunto,justica,instancia,orgao,pessoa"
                }
                jtfNome2.setText(resultSet.getString("nome2"));
                jtfNome3.setText(resultSet.getString("nome3"));
                jtfAssunto.setText(resultSet.getString("assunto"));
                jtfJustica.setText(resultSet.getString("justica"));
                jtfInstancia.setText(resultSet.getString("instancia"));
                jtfOrgao.setText(resultSet.getString("orgao"));
                if (resultSet.getString("pessoa").equals("Fisica")){
                    jcbPessoa.setSelectedIndex(0);
                }
                else{
                    jcbPessoa.setSelectedIndex(1);
                }
                jbtnEditar.setEnabled(true);
                
                
               
           }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,"Cliente não encontrado");
            System.out.println(e.getMessage());
            
        }
        finally{
            try {
                if (resultSet!=null){
                    
                    resultSet.close();}
                statement.close();
                conexao.desconectar();
            }
        catch(SQLException e){
                System.out.println(e.getMessage());
        }}
        
        
    }//GEN-LAST:event_btnProcurarNPActionPerformed

    private void jftfDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftfDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftfDataDeNascimentoActionPerformed

    private void jcbPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPessoaActionPerformed

    private void jftfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftfCodigoActionPerformed

    private void jftfCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftfCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftfCepActionPerformed

    private void jftfCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jftfCodigoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jftfCodigoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProcurarCod;
    private javax.swing.JButton btnProcurarNP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCod;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox<String> jcbEstadoCivil;
    private javax.swing.JComboBox<String> jcbPessoa;
    private java.awt.Checkbox jcbStatus;
    private javax.swing.JFormattedTextField jftfCelular;
    private javax.swing.JFormattedTextField jftfCep;
    private javax.swing.JFormattedTextField jftfCodigo;
    private javax.swing.JFormattedTextField jftfCpf;
    private javax.swing.JFormattedTextField jftfDataDeCadastro;
    private javax.swing.JFormattedTextField jftfDataDeNascimento;
    private javax.swing.JFormattedTextField jftfNumeroDeProcesso;
    private javax.swing.JFormattedTextField jftfRg;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JLabel jlblSalvoComSucesso;
    private javax.swing.JTextArea jtaComentarios;
    private javax.swing.JTextField jtfAssunto;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfInstancia;
    private javax.swing.JTextField jtfJustica;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNome2;
    private javax.swing.JTextField jtfNome3;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfOrgao;
    // End of variables declaration//GEN-END:variables
public void desabilitar(){
    jtfNome.setEnabled(false);
     jtfNome2.setEnabled(false);
        jtfNome3.setEnabled(false);
    jftfDataDeNascimento.setEnabled(false);
    jftfTelefone.setEnabled(false);
    jftfRg.setEnabled(false);
    jftfCpf.setEnabled(false);
    jtfNumero.setEnabled(false);
    jftfCodigo.setEnabled(false);
    jtfEndereco.setEnabled(false);
    jbtnLimpar.setEnabled(false);
    jbtnSalvar.setEnabled(false);
    jbtnEditar.setEnabled(false);
    jftfCelular.setEnabled(false);
    jtfComplemento.setEnabled(false);
    jcbEstadoCivil.setEnabled(false);
    jtaComentarios.setEnabled(false);
    jcbStatus.setEnabled(false);
     jftfCep.setEnabled(false);
      jtfAssunto.setEnabled(false);
        jtfJustica.setEnabled(false);
        jtfInstancia.setEnabled(false);
        jtfOrgao.setEnabled(false);
        jcbPessoa.setEnabled(false);
    
        
    
    
}
 public void habilitar(){
     
        jtfNome.setEnabled(true);
        jtfNome2.setEnabled(true);
        jtfNome3.setEnabled(true);
        jftfDataDeNascimento.setEnabled(true);
        jftfTelefone.setEnabled(true);
        jftfRg.setEnabled(true);
        jftfCpf.setEnabled(true);
        jtfNumero.setEnabled(true);
        jftfCodigo.setEnabled(false);
        jtfEndereco.setEnabled(true);
        jbtnLimpar.setEnabled(true);
        jbtnSalvar.setEnabled(true);
        jbtnEditar.setEnabled(true);
        jftfCelular.setEnabled(true);
        jtfComplemento.setEnabled(true);
        jcbEstadoCivil.setEnabled(true);
        jtaComentarios.setEnabled(true);
        jtfEmail.setEnabled(true);
        jcbStatus.setEnabled(true);
        jftfCep.setEnabled(true);
        jtfAssunto.setEnabled(true);
        jtfJustica.setEnabled(true);
        jtfInstancia.setEnabled(true);
        jtfOrgao.setEnabled(true);
        jcbPessoa.setEnabled(true);
        
        }
 public void limpar_campos(){
       //limpando campos
        jtfNome.setText("");
        jtfNome2.setText("");
        jtfNome3.setText("");
        jcbEstadoCivil.setSelectedIndex(0);
        jftfDataDeNascimento.setText("");
        jftfTelefone.setText("");
        jftfCelular.setText("");
        jftfDataDeCadastro.setText("");
        jftfRg.setText("");
        jftfCpf.setText("");
        jcbStatus.setState(true);
        jtfEndereco.setText("");
        jtfNumero.setText("");
        jtfComplemento.setText("");
        jtfEmail.setText("");
        jtaComentarios.setText("");
        jcbStatus.setState(true);
        jftfCodigo.setText("");
        jftfNumeroDeProcesso.setText("");
        jtfAssunto.setText("");
        jtfJustica.setText("");
        jtfInstancia.setText("");
        jtfOrgao.setText("");
        jcbPessoa.setSelectedIndex(0);
        jftfCep.setText("");
     
 }
 
 
}
