/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;






/**
 *
 * @author fernando
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jmMenu = new javax.swing.JMenuBar();
        jmAplicacao = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();
        jmiBaseDeDados = new javax.swing.JMenuItem();
        jmCadastro = new javax.swing.JMenu();
        jmiCadastrar = new javax.swing.JMenuItem();
        jmiListaDeClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jdpAreaDeTrabalho.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1049, Short.MAX_VALUE)
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jmAplicacao.setText("Aplicacao");

        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmAplicacao.add(jmiSair);

        jmiBaseDeDados.setText("Base de dados");
        jmiBaseDeDados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jmiBaseDeDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBaseDeDadosActionPerformed(evt);
            }
        });
        jmAplicacao.add(jmiBaseDeDados);

        jmMenu.add(jmAplicacao);

        jmCadastro.setText("Cadastros");

        jmiCadastrar.setText("Cadastrar/Procurar cliente");
        jmiCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadastrar);

        jmiListaDeClientes.setText("Lista de clientes");
        jmiListaDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListaDeClientesActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiListaDeClientes);

        jmMenu.add(jmCadastro);

        setJMenuBar(jmMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpAreaDeTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarActionPerformed
        // TODO add your handling code here:
        Cadastro obj = new Cadastro();
        jdpAreaDeTrabalho.add(obj);
        obj.setLocation(100,100);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiCadastrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(Principal.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiListaDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListaDeClientesActionPerformed
        // TODO add your handling code here:
        ListaDeClientes obj= new ListaDeClientes();
        this.jdpAreaDeTrabalho.add(obj);
        obj.setLocation(450,100);
        obj.setVisible(true);
    }//GEN-LAST:event_jmiListaDeClientesActionPerformed

    private void jmiBaseDeDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBaseDeDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiBaseDeDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    private javax.swing.JMenu jmAplicacao;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuBar jmMenu;
    private javax.swing.JMenuItem jmiBaseDeDados;
    private javax.swing.JMenuItem jmiCadastrar;
    private javax.swing.JMenuItem jmiListaDeClientes;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables
}
